const Allappdata =[
    {
		id: 1,
		img:'/images/featured-app/feat-img1.png',
		title: 'Jet attack move',
		slug: 'jet-attack-move',
        para: 'Arcade Air Combat',
        date: 'Oct 20 2023',
        type: ['popularapp','newapp', 'games', 'ios', 'browsehistory','last24'],
        slide: ['/images/inner-slider/slide202.png', '/images/inner-slider/slide203.jpg', '/images/inner-slider/slide204.png', '/images/inner-slider/slide205.png', '/images/inner-slider/slide206.png'],
        slidenum: 2.5,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 2,
		img:'/images/featured-app/feat-img2.png',
		title: 'WhatsApp Messenger',
		slug: 'whatsApp-messenger',
        para: 'WhatsApp LLC',
        date: 'Oct 20 2023',
        type: ['android', 'popularapp','communication', 'recentapp', 'newapp', 'browsehistory','last24'],
        slide: ['/images/inner-slider/slide42.png', '/images/inner-slider/slide43.png', '/images/inner-slider/slide44.png','/images/inner-slider/slide45.png','/images/inner-slider/slide46.png', '/images/inner-slider/slide47.png'],
        slidenum: 2.5,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 3,
		img:'/images/featured-app/feat-img3.png',
		title: 'Grim Soul: Dark Survival RPG',
		slug: 'grim-soul-dark-survival-RPG',
        para: 'Brickworks games limited',
        date: 'Oct 20 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'browsehistory', 'featuredapp', 'musthaveapp', ,'last24'],
        slide: ['/images/inner-slider/slide73.png','/images/inner-slider/slide74.png' , '/images/inner-slider/slide75.png', '/images/inner-slider/slide76.png','/images/inner-slider/slide77.png','/images/inner-slider/slide78.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 4,
		img:'/images/featured-app/feat-img4.png',
		title: 'C-RAM CIWS simulator',
		slug: 'c-ram-ciws-simulator',
        para: 'Anti Air Gun, Air Defense Game',
        date: 'Oct 20 2023',
        type: ['games','ios', 'popularapp', 'newapp', ,'last24', 'browsehistory'],
        slide: ['/images/inner-slider/slide196.png','/images/inner-slider/slide197.png', '/images/inner-slider/slide198.png', '/images/inner-slider/slide199.png', '/images/inner-slider/slide200.png', '/images/inner-slider/slide201.png'],
        slidenum: 2.5,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 5,
		img:'/images/featured-app/feat-img5.png',
		title: 'War Thunder Mobile',
		slug: 'war-thunder-mobile',
        para: 'Tanks, ships and aircraft',
        date: 'Oct 20 2023',
        type: ['games', 'ios', 'popularapp', 'newapp', 'browsehistory','last24'],
        slide: ['/images/inner-slider/slide190.png','/images/inner-slider/slide191.png', '/images/inner-slider/slide192.png', '/images/inner-slider/slide193.png', '/images/inner-slider/slide194.png', '/images/inner-slider/slide195.png'],
        slidenum: 1.6,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 6,
		img:'/images/featured-app/feat-img6.png',
		title: 'Road to Valor: Empires',
		slug: 'road-to-valor-empires',
        para: 'Dreamotion Inc.',
        date: 'Oct 20 2023',
        type: ['games', 'android', 'popularapp', 'newapp','last24', 'browsehistory'],
        slide: ['/images/inner-slider/slide13.png','/images/inner-slider/slide14.png', '/images/inner-slider/slide15.png', '/images/inner-slider/slide16.png' ],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 7,
		img:'/images/featured-app/feat-img7.png',
		title: 'Craft of Survival - Gladiators',
		slug: 'craft-of-survival-gladiators',
        para: '101XP LIMITED',
        date: 'Oct 20 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'newapp', 'browsehistory', 'featuredapp', 'musthaveapp', ,'last24' ],
        slide: ['/images/inner-slider/slide1.png', '/images/inner-slider/slide2.jpg', '/images/inner-slider/slide3.png', '/images/inner-slider/slide4.png', '/images/inner-slider/slide5.png', '/images/inner-slider/slide6.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 8,
		img:'/images/featured-app/feat-img8.png',
		title: 'NordVPN – fast VPN for privacy',
		slug: 'nordVPN–fast-vpn-for-privacy',
        para: 'Nord Security',
        date: 'Oct 20 2023',
        type: ['security', 'android', 'popularapp','recentapp', 'newapp','last24'],
        slide: ['/images/inner-slider/slide58.png','/images/inner-slider/slide59.png','/images/inner-slider/slide60.png','/images/inner-slider/slide61.png', '/images/inner-slider/slide62.png','/images/inner-slider/slide63.png'],
        slidenum: 6,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 9,
		img:'/images/featured-app/feat-img9.png',
		title: 'Kaspersky Fast Secure VPN',
		slug: 'kaspersky-fast-secure-vpn',
        para: 'Kaspersky ME',
        date: 'Oct 20 2023',
        type: ['security', 'android', 'popularapp', 'newapp','last24'],
        slide: ['/images/inner-slider/slide24.png', '/images/inner-slider/slide25.png', '/images/inner-slider/slide26.png', '/images/inner-slider/slide27.png', '/images/inner-slider/slide28.png', '/images/inner-slider/slide29.png'],
        slidenum: 5.7,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
    {
		id: 10,
		img:'/images/featured-app/feat-img10.png',
		title: 'Conflict of Nations: WW3 Game',
		slug: 'conflict-of-nations-ww3-game',
        para: 'Dorado Games / DOG Productions Ltd',
        date: 'Oct 20 2023',
        type: ['games', 'android', 'popularapp', 'recentapp', 'newapp', 'browsehistory','last24'],
        slide: ['/images/inner-slider/slide7.png', '/images/inner-slider/slide8.png', '/images/inner-slider/slide9.png', '/images/inner-slider/slide10.png', '/images/inner-slider/slide11.png', '/images/inner-slider/slide12.png'],
        slidenum: 6,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
      {
		id: 11,
		img:'/images/featured-app/newapp-1.png',
		title: 'iTop Vpn',
		slug: 'itop-vpn',
        para: 'Techway',
		date: 'Oct 11, 2023',
        type: ['security', 'android', 'newapp','last24'],
        slide: ['/images/inner-slider/slide18.png', '/images/inner-slider/slide19.png', '/images/inner-slider/slide20.png', '/images/inner-slider/slide21.png', '/images/inner-slider/slide22.png', '/images/inner-slider/slide23.png'],
        slidenum: 6,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
      {
		id: 12,
		img:'/images/featured-app/new-app2.png',
		title: 'Kaspersky VPN & Antivirus',
		slug: 'kaspersky-vpn-antivirus',
        para: 'Kaspersky ME',
		date: 'Oct 11, 2023',
        type: ['security', 'android', 'popularapp', 'newapp','last24'],
        slide: ['/images/inner-slider/slide30.png','/images/inner-slider/slide31.png', '/images/inner-slider/slide32.png', '/images/inner-slider/slide33.png', '/images/inner-slider/slide34.png', '/images/inner-slider/slide35.png'],
        slidenum: 6, 
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
      {
		id: 13,
		img:'/images/featured-app/new-app3.png',
		title: 'Turbo VPN - Secure VPN Proxy',
		slug: 'turbo-vpn-secure-vpn-proxy',
        para: 'Innovative Connecting',
		date: 'Oct 11,2023',
        type: ['security', 'android', 'popularapp','recentapp', 'newapp','last24'],
        slide: ['/images/inner-slider/slide36.png','/images/inner-slider/slide37.png', '/images/inner-slider/slide38.png', '/images/inner-slider/slide39.png', '/images/inner-slider/slide40.png', '/images/inner-slider/slide41.png'],
        slidenum: 6,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
      {
		id: 14,
		img:'/images/featured-app/new-app4.png',
		title: 'TunnelBear VPN',
		slug: 'tunnelBear-vpn',
        para: 'TunnelBear, LLC',
		date: 'Sep 30, 2023',
        type: ['security', 'android', 'popularapp','recentapp', 'newapp','last24'],
        slide: ['/images/inner-slider/slide48.png','/images/inner-slider/slide49.png', '/images/inner-slider/slide50.png', '/images/inner-slider/slide51.png'],
        slidenum: 6,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
      {
		id: 15,
		img:'/images/featured-app/new-app5.png',
		title: 'ExpressVPN: VPN Fast & Secure',
		slug: 'epressvpn-vpn-fast-secure',
        para: 'ExpressVPN',
		date: 'Sep 30, 2023',
        type: ['security', 'android', 'popularapp','recentapp', 'newapp','last24'],
        slide: ['/images/inner-slider/slide52.png','/images/inner-slider/slide53.png', '/images/inner-slider/slide54.png', '/images/inner-slider/slide55.png', '/images/inner-slider/slide56.png', '/images/inner-slider/slide57.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
	  },
      {
		id: 16,
		img:'/images/featured-app/security-1.png',
		title: 'VPN - Super Unlimited Proxy',
		slug: 'vpn-super-unlimited-proxy',
        para: 'VPN Super Inc',
		date: 'Sep 30, 2023',
        type: ['security', 'android', 'popularapp','recentapp', 'newapp','last24'],
        slide: ['/images/inner-slider/slide64.png', '/images/inner-slider/slide65.png', '/images/inner-slider/slide66.png', '/images/inner-slider/slide67.png'],
        version: 6,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
		id: 17,
		img:'/images/featured-app/security-2.png',
		title: 'Secure VPN－Safer Internet',
		slug: 'secure-vpn-safer-internet',
        para: 'Signal Lab',
		date: 'Sep 30, 2023',
        type: ['security', 'android', 'popularapp','recentapp', 'newapp','last24'],
        slide: ['/images/inner-slider/slide68.png','/images/inner-slider/slide69.png', '/images/inner-slider/slide70.png', '/images/inner-slider/slide71.png', '/images/inner-slider/slide72.png'],
        slidenum: 6,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
		id: 18,
		img:'/images/featured-app/cho-1.png',
		title: 'Last Shelter: Survival',
		slug: 'last-shelter-survival',
        para: 'Long Tech Network Limited',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'featuredapp', 'musthaveapp','last24', 'browsehistory'],
        slide: ['/images/inner-slider/slide79.png','/images/inner-slider/slide80.png', '/images/inner-slider/slide81.png', '/images/inner-slider/slide82.png', '/images/inner-slider/slide83.png', '/images/inner-slider/slide84.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
		id: 19,
		img:'/images/featured-app/cho-2.png',
		title: 'Dawn of Zombies: Survival Game',
		slug: 'dawn-of-zombies-survival-game',
        para: 'Royal Ark',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'featuredapp', 'musthaveapp','last24', 'browsehistory'],
        slide: ['/images/inner-slider/slide85.png', '/images/inner-slider/slide86.png', '/images/inner-slider/slide87.png', '/images/inner-slider/slide88.png', '/images/inner-slider/slide89.png'],
        slidenum: 1.8,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
		id: 20,
		img:'/images/featured-app/cho-3.png',
		title: 'Merge Survival : Wasteland',
		slug: 'merge-survival-wasteland',
        para: 'StickyHands Inc.',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'browsehistory', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide91.png', '/images/inner-slider/slide92.png', '/images/inner-slider/slide93.png', '/images/inner-slider/slide94.png', '/images/inner-slider/slide95.png','/images/inner-slider/slide96.png'],
        slidenum: 6,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
		id: 21,
		img:'/images/featured-app/cho-4.png',
		title: 'AoD Vikings: Valhalla Game',
		slug: 'aod-vikings-valhalla-game',
        para: 'RoboBot Studio',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'browsehistory', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide97.png', '/images/inner-slider/slide98.png', '/images/inner-slider/slide99.png', '/images/inner-slider/slide100.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    
    {
		id: 22,
		img:'/images/featured-app/cho-5.png',
		title: 'Viking Clan: Ragnarok',
		slug: 'viking-clan-ragnarok',
        para: 'Kano Games',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'browsehistory', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide101.png', '/images/inner-slider/slide102.png', '/images/inner-slider/slide103.png', '/images/inner-slider/slide104.png', '/images/inner-slider/slide105.png', '/images/inner-slider/slide106.png'],
        slidenum: 2,
        verssion:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
		id: 23,
		img:'/images/featured-app/cho-6.png',
		title: 'Vikings: War of Clans',
		slug: 'vikings-war-of-clans',
        para: 'Plarium LLC',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'browsehistory', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide107.png', '/images/inner-slider/slide108.png', '/images/inner-slider/slide109.png', '/images/inner-slider/slide110.png', '/images/inner-slider/slide111.png', '/images/inner-slider/slide112.png'],
        slidenum: 2.1,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
		id: 24,
		img:'/images/featured-app/cho-7.png',
		title: 'Asphalt 9: Legends',
		slug: 'asphalt-9-legends',
        para: 'Gameloft SE',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'featuredapp', 'musthaveapp','last24', 'browsehistory'],
        slide: ['/images/inner-slider/slide113.png', '/images/inner-slider/slide114.png', '/images/inner-slider/slide115.png', '/images/inner-slider/slide116.png', '/images/inner-slider/slide117.png', '/images/inner-slider/slide118.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
		id: 25,
		img:'/images/featured-app/cho-8.png',
		title: 'Modern Tanks: War Tank Games',
		slug: 'modern-tanks-war-tank-games',
        para: 'XDEVS LTD',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'featuredapp', 'musthaveapp','last24', 'browsehistory'],
        slide: ['/images/inner-slider/slide119.png', '/images/inner-slider/slide120.png', '/images/inner-slider/slide121.png', '/images/inner-slider/slide122.png', '/images/inner-slider/slide119.png', '/images/inner-slider/slide120.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 26,
        img:'/images/featured-app/cho-9.png',
        title: 'Call of Duty Mobile Season 8',
        slug: 'call-of-duty-mobile-season-8',
        para: 'Activision Publishing, Inc.',
        date: 'Sep 30, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'browsehistory', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide123.png', '/images/inner-slider/slide124.png', '/images/inner-slider/slide125.png', '/images/inner-slider/slide126.png', '/images/inner-slider/slide127.png', '/images/inner-slider/slide128.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 27,
        img:'/images/featured-app/cho-10.png',
        title: 'Future Tanks: War Tank Game',
        slug: 'future-tanks-war-tank-game',
        para: 'XDEVS LTD',
        date: 'Sep 30, 2023',
        type: ['games', 'android','editorchoice', 'recentapp', 'newapp', 'featuredapp', 'musthaveapp', 'browsehistory'],
        slide: ['/images/inner-slider/slide129.png', '/images/inner-slider/slide130.png', '/images/inner-slider/slide131.png', '/images/inner-slider/slide132.png', '/images/inner-slider/slide133.png', '/images/inner-slider/slide129.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 28,
        img:'/images/featured-app/game-1.png',
        title: 'Tank Force: War games of Blitz',
        slug: 'tank-force-war-games-of-blitz',
        para: 'XDEVS LTD',
        date: 'Sep 25, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'featuredapp', 'musthaveapp', 'browsehistory'],
        slide: ['/images/inner-slider/slide134.png', '/images/inner-slider/slide135.png', '/images/inner-slider/slide136.png', '/images/inner-slider/slide137.png', '/images/inner-slider/slide138.png', '/images/inner-slider/slide139.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 29,
        img:'/images/featured-app/game-2.png',
        title: 'Furious Tank: War of Worlds',
        slug: 'furious-tank-war-of-worlds',
        para: 'Click.18 Mobile',
        date: 'Sep 25, 2023',
        type: ['games', 'android','editorchoice', 'recentapp', 'newapp', 'featuredapp', 'musthaveapp', 'browsehistory'],
        slide:['/images/inner-slider/slide140.png', '/images/inner-slider/slide141.png', '/images/inner-slider/slide142.png', '/images/inner-slider/slide143.png', '/images/inner-slider/slide144.png', '/images/inner-slider/slide145.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 30,
        img:'/images/featured-app/worldwar8.png',
        title: 'Need for Speed™ No Limits',
        slug: 'need-for-speed™-no-limits',
        para: 'ELECTRONIC ARTS',
        date: 'Nov 24, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'newapp', 'browsehistory', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide146.png', '/images/inner-slider/slide147.png','/images/inner-slider/slide148.png', '/images/inner-slider/slide149.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 31,
        img:'/images/featured-app/worldwar7.png',
        title: 'CSR 2 Realistic Drag Racing',
        slug: 'csr-2-realistic-drag-racing',
        para: 'NaturalMotionGames Ltd',
        date: 'Nov 24, 2023',
        type: ['games', 'android', 'popularapp','editorchoice', 'recentapp', 'browsehistory', 'featuredapp', 'musthaveapp',,'last24'],
        slide: ['/images/inner-slider/slide150.png', '/images/inner-slider/slide151.png', '/images/inner-slider/slide152.png', '/images/inner-slider/slide153.png', '/images/inner-slider/slide150.png', '/images/inner-slider/slide151.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 32,
        img:'/images/featured-app/worldwar6.png',
        title: 'Hot Wheels Unlimited',
        slug: 'hot-wheels-unlimited',
        para: 'Budge Studios',
        date: 'Nov 24, 2023',
        type: ['games', 'android','editorchoice', 'recentapp', 'browsehistory', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide154.png', '/images/inner-slider/slide155.png', '/images/inner-slider/slide156.png', '/images/inner-slider/slide157.png', '/images/inner-slider/slide158.png', '/images/inner-slider/slide159.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id:33,
        img:'/images/featured-app/worldwar5.png',
        title: 'Rising: War for Dominion',
        slug: 'rising-war-for-dominion',
        para: 'NEWHOPE TECH PTE.LTD.',
        date: 'Nov 24, 2023',
        type: ['games', 'android','popularapp','editorchoice', 'recentapp', 'featuredapp', 'musthaveapp','browsehistory'],
        slide: ['/images/inner-slider/slide160.png', '/images/inner-slider/slide161.png', '/images/inner-slider/slide162.png', '/images/inner-slider/slide163.png', '/images/inner-slider/slide164.png', '/images/inner-slider/slide165.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 34,
        img:'/images/featured-app/worldwar4.png',
        title: 'World of War Machines - WW2',
        slug: 'world-of-war-machines-ww2',
        para: 'Bigbreakgames',
        date: 'Nov 24, 2023',
        type: ['games', 'android','editorchoice', 'recentapp', 'browsehistory', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide166.png', '/images/inner-slider/slide167.png', '/images/inner-slider/slide168.png', '/images/inner-slider/slide169.png', '/images/inner-slider/slide170.png', '/images/inner-slider/slide171.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 35,
        img:'/images/featured-app/worldwar3.png',
        title: 'Road to Valor: World War II',
        slug: 'road-to-valor-world-war-II',
        para: 'Dreamotion Inc.',
        date: 'Nov 24, 2023',
        type: ['games', 'android','popularapp','editorchoice', 'recentapp', 'browsehistory', 'featuredapp', 'musthaveapp',,'last24'],
        slide: ['/images/inner-slider/slide172.png','/images/inner-slider/slide173.png', '/images/inner-slider/slide174.png', '/images/inner-slider/slide175.png', '/images/inner-slider/slide177.png'],
        slidenum: 4,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 36,
        img:'/images/featured-app/worldwar2.png',
        title: 'World War Armies: WW2 PvP RTS',
        slug: 'world-war-armies-ww2-pvp-rts',
        para: 'Hypemasters, Inc.',
        date: 'Nov 24, 2023',
        type: ['games', 'android','popularapp','editorchoice', 'recentapp', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide178.png', '/images/inner-slider/slide179.png', '/images/inner-slider/slide180.png', '/images/inner-slider/slide181.png', '/images/inner-slider/slide182.png', '/images/inner-slider/slide183.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id: 37,
        img:'/images/featured-app/worldwar1.png',
        title: 'World War Heroes — WW2 PvP FPS',
        slug: 'world-war-heroes—ww2-pvp-fps',
        para: 'Azur Interactive Games Limited',
        date: 'Nov 24, 2023',
        type: ['games', 'android','popularapp','editorchoice', 'recentapp', 'browsehistory', 'featuredapp', 'musthaveapp','last24'],
        slide: ['/images/inner-slider/slide184.png', '/images/inner-slider/slide185.png', '/images/inner-slider/slide186.png', '/images/inner-slider/slide187.png', '/images/inner-slider/slide188.png', '/images/inner-slider/slide189.png'],
        slidenum: 2,
        version:5.4,
        categories: 'Games',
        Platform: 'Android',
        Downloads: 143,
        Licence : 'Free',
    },
    {
        id:38,
        type: ['design', 'entertainment','education','email', 'finance','internet','ittools', 'media', 'tools', 'travel','window','mac','linux'],
        error: 'No Record Found',
    }

]


export async function
 GET(request){
    return new Response(JSON.stringify(Allappdata),{
        headers: {'Content-Type' : 'application/json'},
    });
}
